import{i as a,S as u}from"./assets/vendor-5b791d57.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function e(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(t){if(t.ep)return;t.ep=!0;const o=e(t);fetch(t.href,o)}})();function f(r){if(r.hits.length==0)a.error({message:"Sorry, there are no images matching your search query. Please try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"});else{const s=r.hits.map(e=>`<li class="photos-list-item">
            <a class="photos-list-link" href="${e.largeImageURL}">
            <img class="photo" src="${e.webformatURL}" alt="${e.tags}"/>
            </a>
            <ul class="photo-information-container">
            <li class="item-photo-information-container"><p><span class="accent">Likes</span></br>${e.likes}</p></li>
            <li class="item-photo-information-container"><p><span class="accent">Views</span></br>${e.views}</p></li>
            <li class="item-photo-information-container"><p><span class="accent">Comments</span></br>${e.comments}</p></li>
            <li class="item-photo-information-container"><p><span class="accent">Downloads</span></br>${e.downloads}</p></li>
            </ul>
            </li>`).join("");m.insertAdjacentHTML("beforeend",s),h.refresh()}}function d(){const r=l.elements.search.value.trim().split(",").join("+"),s="42958097-9b7fc012df8e9620edb2fab69",e=new URLSearchParams({key:s,q:[r],image_type:"photo",orientation:"horizontal",safesearch:!0});return g(),fetch(`https://pixabay.com/api/?${e}`).then(n=>{if(!n.ok)throw new Error(n.status);return n.json()})}const l=document.querySelector(".search-form"),m=document.querySelector(".gallery"),h=new u(".photos-list-link",{captionsData:"alt",captionPosition:"bottom",captionDelay:250}),c=document.querySelector(".loader");c.style.display="none";const g=()=>{c.style.display="flex"},p=()=>{c.style.display="none"};l.addEventListener("submit",y);function y(r){r.preventDefault(),m.innerHTML="",r.target.elements.search.value.trim()!==""?(d().then(e=>{f(e),p()}).catch(e=>{console.log(e),p(),a.error({message:"Sorry, an error occurred while loading. Please try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"})}),l.reset()):a.show({message:"Please complete the field!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"})}
//# sourceMappingURL=commonHelpers.js.map
